# Generated by Django 3.1.1 on 2020-10-04 15:14

from django.db import migrations, models
import django.db.models.deletion
import ulid.api.api


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255, unique=True, verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='Uploadfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='Name of the file')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('proj_id', models.CharField(max_length=255, verbose_name='Project Name')),
                ('heading', models.IntegerField(default=0, help_text='*The numbers are clockwise from north (=0) (east = 90, south = 180, west = 270)', verbose_name='Direction of the wind turbine (0 to 360)')),
                ('hub_height', models.FloatField(default=100, verbose_name='Hub height(m)')),
                ('blade_length', models.FloatField(default=80, verbose_name='Blade length(m)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('appearance', models.BooleanField(help_text='*Check the box if you want the blade rotation position to be random.', verbose_name='Position of the blade')),
                ('color', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gewind_en.color', verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turbine_name', models.CharField(blank=True, help_text='a', max_length=32, verbose_name='Wind turbine name')),
                ('lon', models.FloatField(help_text='a', verbose_name='Longitude')),
                ('lat', models.FloatField(help_text='a', verbose_name='Latitude')),
                ('export_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gewind_en.projectinfo', verbose_name='export_id')),
            ],
        ),
    ]
