# Generated by Django 3.1.1 on 2020-10-05 04:43

from django.db import migrations, models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('gewind_en', '0002_auto_20201005_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='blade_length',
            field=models.FloatField(default=80, verbose_name='Blade length (m)'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='heading',
            field=models.IntegerField(default=0, help_text='*The numbers are clockwise from north (north = 0, east = 90, south = 180, west = 270)', verbose_name='Heading (0 to 360)'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='hub_height',
            field=models.FloatField(default=100, verbose_name='Hub height (m)'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
    ]
