# Generated by Django 3.1.1 on 2020-10-05 04:48

from django.db import migrations, models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('gewind_en', '0003_auto_20201005_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='heading',
            field=models.IntegerField(default=0, help_text='*North = 0, East = 90, South = 180, West = 270', verbose_name='Heading (0 to 360)'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
    ]
