# Generated by Django 3.1.1 on 2020-10-04 15:13

from django.db import migrations, models
import django.db.models.deletion
import ulid.api.api


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255, unique=True, verbose_name='色')),
            ],
        ),
        migrations.CreateModel(
            name='Uploadfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='ファイル')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='ファイル名')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('proj_id', models.CharField(help_text='※Google Earth上に表示される名前です。', max_length=255, verbose_name='プロジェクト名')),
                ('heading', models.IntegerField(default=0, help_text='※数字は北（=0）から時計回り（参考：東=90, 南=180, 西=270）', verbose_name='風車の向き(0～360)')),
                ('hub_height', models.FloatField(default=100, verbose_name='ハブ高(m)')),
                ('blade_length', models.FloatField(default=80, verbose_name='ブレードの長さ(m)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('appearance', models.BooleanField(help_text='※ブレードの回転位置をランダムにする場合はチェックを入れる。', verbose_name='ブレードの回転位置')),
                ('color', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gewind.color', verbose_name='風車の色')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turbine_name', models.CharField(blank=True, help_text='a', max_length=32, verbose_name='風車の名称')),
                ('lon', models.FloatField(help_text='a', verbose_name='経度')),
                ('lat', models.FloatField(help_text='a', verbose_name='緯度')),
                ('export_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gewind.projectinfo', verbose_name='出力ID')),
            ],
        ),
    ]
